### ISSUE TITLE
How to merge 

### ISSUE THREAD

**Issue by Ahrle** [selbetar/askfmArchiver#15]
Hey, Askfm is having problems with 500 server errors, but trying to continue using -p flag doesn't seem to work?

f:\ast>askfmarchiver.exe -u [username] -a
[03:25:06 INF] Application is Starting: Archival Service
885
Progress: 5,65%   [03:25:37 FTL] Response status code does not indicate success: 500 (Internal Server Error).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at System.Net.Http.HttpClient.GetStringAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at askfmArchiver.Utils.NetworkManager.HttpRequest(String url)
   at askfmArchiver.Parser.GetHtmlDoc(String url)
   at askfmArchiver.Parser.GetNextPage(HtmlDocument html)
   at askfmArchiver.Parser.ParsePage(HtmlDocument html)
   at askfmArchiver.Parser.Parse()
[03:25:37 ERR] Attempting to commit 75 answers to the database.
[03:25:37 ERR] Successfully committed 75 answers to the database.

followed by

f:\ast>askfmarchiver.exe -u [username] -a -p75
[03:25:43 INF] Application is Starting: Archival Service
810
[03:25:48 ERR] ParsePage(): articleNodes are null. html is:
HtmlAgilityPack.HtmlDocument
Progress: 100%   Finished Parsing 0 answers.
[03:25:48 INF] Application is Done: Archival Service

Am I doing something wrong?

**Comment by selbetar** [comment]
`askfmarchiver.exe -u [username] -a -p75`

the flag `-p` takes a unix timestamp. You can check if you provided a correct value by going to `https://ask.fm/<username>?older=<p>`.

Examples:
```
https://ask.fm/askfm?older=1729884034
https://ask.fm/askfm?older=75
```
you can inspect the database file and find the oldest timestamp stored in there and use that as a a value for `-p`.

That said, this tool is no longer maintained, but I plan on releasing a new one soon that can archive an entire profile including chats/threads and it will be faster and will have better recovery mechanism for errors and interruptions.

**Comment by Ahrle** [comment]
Thanks! You think it'll be out soon? The site shuts down in 9 days

**Comment by marsonal** [comment]
when will you release that new tool? , it is only a week remaining now

**Comment by selbetar** [comment]
https://github.com/selbetar/askfm-archiving-scripts
